services:
  - type: web
    name: hotel-app
    env: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: LOG_CHANNEL
        value: errorlog
      - key: SESSION_DRIVER
        value: cookie
      - key: DB_CONNECTION
        value: pgsql